Implementation news display
AndreKuts/TTITransition pull request #3
Opened 2018-04-06 06:59 UTC by AndreKuts

segment controller work

2018-04-06 07:48 UTC, AndreySak requested changes

2018-04-06 07:48 UTC, AndreySak commented on Podfile
> +	pod 'Alamofire', '~> 4.7'
в постановке задания сказано не использовать сторонние библиотеки - удалям

2018-04-06 07:48 UTC, AndreySak commented on TTITransition/Models/NewsItem.swift
> +enum Segment {
старайся держать каждый класс в отдельном файле и посмотри конвеншн по наименованию полей инамов. сейчас  не верно

2018-04-06 07:48 UTC, AndreySak commented on TTITransition/Models/NewsItem.swift
> +
просмотри ВСЕ файлы и удали не нужные пустые строчки. у меня палец устает скроллить

2018-04-06 07:48 UTC, AndreySak commented on TTITransition/ViewControllers/DetailsViewController.swift
> +        guard news != nil else { return }
попробуй вот так guard  !news else {return}

2018-04-06 07:48 UTC, AndreySak commented on TTITransition/ViewControllers/DetailsViewController.swift
> +        if let img = news?.image {
анвраппинг можно добавить в guard через запятую

2018-04-06 07:48 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    var updateSegment = Segment.New {
посмотри гайдлайны что я скинул. вот так как ты сделал - не делают

2018-04-06 07:48 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    var arrItem = [NewsItem(image: UIImage(named: "010-worldwide")!, text: "aasd asd asd as das dadfgsdf gsd asd as das dadfgsdf gdsfgsd asd as das dadfgsdf gdsfgdsfg sdfg sdfg"),
назови массив нормально

2018-04-06 07:48 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    var updateSegment = Segment.New {
ты назвал переменную как метод, может лучше тогда с

2018-04-06 11:33 UTC, AndreKuts commented
kek

2018-04-08 18:36 UTC, AndreySak commented on Podfile
> +target 'TTITransition' do
удали этот файл

2018-04-08 18:36 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +weak var TableViewDelegate : UITableViewController!
переменные с большой буквы не начинаются. названине переменной вводит в заблуждение с ее типом.

2018-04-08 18:36 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: NewsTableViewCell.reuseIdentifier, for: indexPath) as! NewsTableViewCell
!

2018-04-08 18:36 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +            self.allNews[indexPath.row].isLiked = !self.allNews[indexPath.row].isLiked
утечка памяти

2018-04-08 18:36 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +            TableViewDelegate.tableView.reloadRows(at: [indexPath], with: UITableViewRowAnimation.none)
так вот зачем тебе эта переменная....
https://stackoverflow.com/questions/27014928/how-to-set-a-weak-reference-to-a-closure-function-in-swift?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa - изучить

2018-04-08 18:36 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +        likeBtn.backgroundColor = color
переменная color объявлена далеко от ее единственного примененияю будет красивее, если она будет обьявлена строчкой выше.

2018-04-08 18:36 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
>              let destVC = segue.destination as! DetailsViewController
!

2018-04-09 08:08 UTC, AndreySak approved these changes

2018-04-09 08:09 UTC, merged