Implement paginations
AndreKuts/TTITransition pull request #7
Opened 2018-04-14 08:16 UTC by AndreKuts

2018-04-14 08:47 UTC, AndreySak requested changes

2018-04-14 08:47 UTC, AndreySak commented on TTITransition/Models/APIService/NewsAPIService.swift
> +            guard list.list.count > howMuchMore else { return }
объедини в один гуард

2018-04-14 08:47 UTC, AndreySak commented on TTITransition/Models/APIService/NewsAPIService.swift
> +                guard let url = URL(string: urlStr) else {
можно вынести let urlStr = "\(strongSelf.baseUrl)/v0/item/\(id).json" выше, до utilityQueue.async { [weak self] in и объелинить два гуард в один

2018-04-14 08:47 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    private var numberNewsUploaded = 20 {
y тебя в начале загружено ноль, а тут ты написал, что у тебя загружено 20

2018-04-14 08:47 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +        numberNewsUploaded = 20
у тебя уже по дефолту стоит 20

2018-04-14 08:47 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +                strongSelf.allNews = strongSelf.newsService.loadNewsItems(for: .best, howMuchMore
var newsSource: NewsSource!

switch (segmentedControl) {
case 1: newsSource = .top
case 2: newsSource = .best
....
} 

utilityQueue.async { [weak self] in
                  guard let strongSelf = self else { return }	
	                  guard let strongSelf = self else { return }
  strongSelf.allNews = strongSelf.newsService.loadNewsItems(for: newsSource, howMuchMore
 strongSelf.numberNewsUploaded)              }		              }

2018-04-14 08:47 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +        if contentOfSize >= Int(scrollView.contentSize.height) {
а не проще if contentOfSize >= scrollView.contentSize.height - 50?

2018-04-14 09:00 UTC, AndreKuts commented on TTITransition/Models/APIService/NewsAPIService.swift
> +                guard let url = URL(string: urlStr) else {
Ну тогда у меня не будет доступа к strongSelf. И нужно будет ее снова создать

2018-04-14 09:02 UTC, AndreySak commented on TTITransition/Models/APIService/NewsAPIService.swift
> +                guard let url = URL(string: urlStr) else {
let urlStr = "(baseUrl)/v0/item/(id).json"
utilityQueue.async { [weak self] in
а если вот так сделать?

2018-04-18 09:55 UTC, AndreySak requested changes

2018-04-18 09:55 UTC, AndreySak commented on TTITransition/Models/APIService/NewsAPIService.swift
> +
лишняя пустая строка

2018-04-18 09:55 UTC, AndreySak commented on TTITransition/View/NewsTableViewCell.swift
> +    @IBOutlet weak var texts: UILabel!
сколько много текстов ты всунешь в один лейбл?)

2018-04-18 10:32 UTC, merged