Implementation service alamofire
AndreKuts/TTITransition pull request #8
Opened 2018-04-18 15:28 UTC by AndreKuts

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    private var newsSource: NewsSelection = .new
назови enum также как и переменную

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    private var contentOfSize: CGFloat!
название ни о чем не говоритю переводится как содержимое размера

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    private var iconsImageNews: [NewsIcon] = []
два одинковых массива. зачем?

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +            createdIcons(fromNews: arrayDownloadedNews)
createIcons

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    // MARK: - Table view data source
UITableViewDataSource

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    // MARK: - Scroll in TableView
rename

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now()) { [weak self] in
бессмысленно

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +//        iconsImageNews.enumerated().forEach { (offset, newsIcon) in
закоменченный код

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +                if offset < self.arrayDownloadedNews.count {
в гуард

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +
пустые строчки

2018-04-18 15:49 UTC, AndreKuts commented on TTITransition/ViewControllers/DetailsViewController.swift
> +
пустая строка

2018-04-18 15:54 UTC, AndreKuts commented on TTITransition/Models/APIService/NewsAlamofireAPIDelegate.swift
> +import Foundation
много пустых строк

2018-04-18 15:54 UTC, AndreKuts commented on TTITransition/Models/APIService/NewsAlamofireAPIDelegat.swift
> +
пустая строка

2018-04-18 15:54 UTC, AndreKuts commented on TTITransition/Models/APIService/NewsAPIServiceProtocol.swift
> +    init(standartDelegate: NewsServiceDelegate?, alamofireDelegat: NewsAlamofireServiceDelegate?)
переделать что бы у меня не бомбило

2018-04-18 15:54 UTC, AndreKuts commented on TTITransition/Models/APIService/NewsAPIService.swift
> +    required init(standartDelegate: NewsServiceDelegate?, alamofireDelegat: NewsAlamofireServiceDelegate?) {
фу фу фу

2018-04-19 13:38 UTC, AndreySak requested changes

2018-04-19 13:38 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    @IBOutlet weak var loadingNewNewsIndicator: UIActivityIndicatorView!
плохое название перем

2018-04-19 13:38 UTC, AndreySak commented on TTITransition/ViewControllers/NewsTableViewController.swift
> +    private var sizeScrollView: CGFloat!
зачем тебе запоминать size если ты можешь его взять через scrollView.frame.size

2018-04-19 13:38 UTC, AndreySak commented on TTITransition/Models/APIService/NewsAlamofireAPIService.swift
> +                Alamofire.request(url).responseJSON(completionHandler: { (response) in
если один параметр, то скобки не ставят

2018-04-19 13:38 UTC, AndreySak commented on TTITransition/Models/APIService/NewsAlamofireAPIDelegate.swift
> +
так и не исправлено

2018-04-19 14:09 UTC, AndreySak approved these changes

2018-04-19 15:59 UTC, merged